window.HEALTH_RESOURCES = [
  {
    id: "bryan-hyman",
    person: "Bryan Johnson",
    personId: "bryan-johnson",
    type: "watch",
    featured: true,
    title: "Bryan Johnson Is Trying to Reverse Death! Here's What He's Actually Found",
    publisher: "Mark Hyman, MD",
    duration: "1h 20m",
    url: "https://www.youtube.com/watch?v=QyyG-PWk0T4",
    youtubeId: "QyyG-PWk0T4",
    note: "A long-form interview that covers diet, sleep, exercise, testing, supplements and the cost/accessibility question. Useful overview, but remember both participants work commercially in health/wellness.",
    evidence: "Interview / first-party claims"
  },
  {
    id: "bryan-evening-exercise",
    person: "Bryan Johnson",
    personId: "bryan-johnson",
    type: "watch",
    featured: false,
    title: "Evening Exercise, Poor Sleep, and Resting Heart Rate",
    publisher: "Bryan Johnson Podcast",
    duration: "46m",
    url: "https://www.youtube.com/watch?v=lKM9OB6qHCE",
    youtubeId: "lKM9OB6qHCE",
    note: "A practical discussion of exercise timing, sleep and resting heart rate. Best treated as an N-of-1 conversation rather than a universal prescription.",
    evidence: "First-party discussion"
  },
  {
    id: "bryan-abc",
    person: "Bryan Johnson",
    personId: "bryan-johnson",
    type: "listen",
    featured: false,
    title: "Bryan Johnson and Kate Tolo want to live forever",
    publisher: "ABC triple j Hack",
    duration: "32m",
    url: "https://www.abc.net.au/triplej/programs/hack/interview-kate-tolo-and-bryan-johnson/107080492",
    note: "An Australian interview that includes harder questions and criticism, useful as a counterweight to Blueprint's own material.",
    evidence: "Independent interview"
  },
  {
    id: "bryan-protocol",
    person: "Bryan Johnson",
    personId: "bryan-johnson",
    type: "read",
    featured: false,
    title: "Bryan Johnson's Protocol",
    publisher: "Blueprint",
    duration: "Reference",
    url: "https://blueprint.bryanjohnson.com/blogs/news/bryan-johnsons-protocol",
    note: "The primary source for his current routine, exercise volume, diet, prescriptions and testing. Detailed, but first-party and commercially connected.",
    evidence: "Primary / first-party"
  },

  {
    id: "lustgarten-epigenetics",
    person: "Michael Lustgarten",
    personId: "michael-lustgarten",
    type: "watch",
    featured: true,
    title: "Tracking and Measuring Biomarkers to Maximize Longevity",
    publisher: "Everything Epigenetics",
    duration: "Long-form",
    url: "https://www.youtube.com/watch?v=9NG_ekdfMU4",
    youtubeId: "9NG_ekdfMU4",
    note: "A clear introduction to Lustgarten's approach: repeated biomarkers, food/exercise tracking, epigenetic clocks and the strengths and limitations of N-of-1 experiments.",
    evidence: "Interview with researcher"
  },
  {
    id: "lustgarten-data-driven",
    person: "Michael Lustgarten",
    personId: "michael-lustgarten",
    type: "watch",
    featured: false,
    title: "Inside Dr. Lustgarten's Data-Driven Blueprint for Longevity",
    publisher: "MyVitalC",
    duration: "57m",
    url: "https://www.youtube.com/watch?v=agwnE_Z6edk",
    youtubeId: "agwnE_Z6edk",
    note: "A newer interview covering his long-term data, diet variability and use of AI to analyse his personal health records. Includes commercial sponsorship.",
    evidence: "Interview / self-tracking"
  },
  {
    id: "lustgarten-blog",
    person: "Michael Lustgarten",
    personId: "michael-lustgarten",
    type: "read",
    featured: false,
    title: "Conquer Aging or Die Trying",
    publisher: "Michael Lustgarten",
    duration: "Ongoing",
    url: "https://michaellustgarten.com/",
    note: "His own archive of blood tests, diet experiments, exercise, HR/HRV and biological-age calculations. Best used for longitudinal raw context rather than headline age scores.",
    evidence: "Primary / first-party"
  },

  {
    id: "svendsen-current",
    person: "Oskar Svendsen",
    personId: "oskar-svendsen",
    type: "read",
    featured: true,
    title: "We tracked down cycling's lost world champion and VO₂ max record holder",
    publisher: "Cycling Weekly",
    duration: "Feature",
    url: "https://www.cyclingweekly.com/news/its-almost-12-years-since-i-quit-i-still-dont-regret-it-we-tracked-down-cyclings-lost-world-champion-and-vo2-max-record-holder",
    note: "The best current profile I found: where Svendsen is now, why he left elite sport, and why an extraordinary VO₂max did not automatically make professional cycling the right life for him.",
    evidence: "Independent interview"
  },
  {
    id: "svendsen-paper",
    person: "Oskar Svendsen",
    personId: "oskar-svendsen",
    type: "read",
    featured: false,
    title: "Temporal changes in determinants of aerobic performance",
    publisher: "Journal of Applied Physiology",
    duration: "Peer-reviewed paper",
    url: "https://journals.physiology.org/doi/full/10.1152/japplphysiol.00798.2018",
    note: "The primary scientific source for his VO₂max series, threshold development and training-volume/intensity distribution.",
    evidence: "Peer-reviewed"
  },

  {
    id: "pascoe-siim-2024",
    person: "Dave Pascoe",
    personId: "dave-pascoe",
    type: "watch",
    featured: true,
    title: "Dave Pascoe Shares His Longevity Routine for Staying Fit In His 60s",
    publisher: "Siim Land",
    duration: "1h 4m",
    url: "https://www.youtube.com/watch?v=K5KmAxnWX5o",
    youtubeId: "K5KmAxnWX5o",
    note: "A useful overview of Pascoe's fitness, diet and routine. Good for extracting the ordinary habits; less useful if copied as a full supplement/biohacking protocol.",
    evidence: "Interview / first-party claims"
  },
  {
    id: "pascoe-siim-2025",
    person: "Dave Pascoe",
    personId: "dave-pascoe",
    type: "watch",
    featured: false,
    title: "Dave Pascoe's 2025 Routine for Staying Ripped at 62",
    publisher: "Siim Land",
    duration: "Interview",
    url: "https://www.youtube.com/watch?v=omNItoJbjxU",
    youtubeId: "omNItoJbjxU",
    note: "A newer snapshot of his exercise and longevity routine. Compare it with the documented medication, testing and cost context in this site's research notes.",
    evidence: "Interview / self-report"
  },
  {
    id: "pascoe-know-your-physio",
    person: "Dave Pascoe",
    personId: "dave-pascoe",
    type: "listen",
    featured: false,
    title: "How I Slowed My Aging with Labs, AI & Strategy",
    publisher: "Know Your Physio",
    duration: "1h 32m",
    url: "https://podcasts.apple.com/au/podcast/dave-pascoe-how-i-slowed-my-aging-with-labs-ai-strategy/id1555295256?i=1000724037129",
    note: "Long-form audio covering fitness, food, testing, AI, supplements and where Pascoe thinks the fundamentals matter more than hype.",
    evidence: "Podcast interview"
  },
  {
    id: "pascoe-appearances",
    person: "Dave Pascoe",
    personId: "dave-pascoe",
    type: "read",
    featured: false,
    title: "Dave Pascoe — Online Appearances",
    publisher: "Dave Pascoe",
    duration: "Index",
    url: "https://www.davepascoe.net/home/online-appearances",
    note: "A large first-party index of interviews and videos. Useful for finding more material, but not an independent quality filter.",
    evidence: "Primary index"
  },

  {
    id: "kelly-nasa-video",
    person: "Scott Kelly",
    personId: "scott-kelly",
    type: "watch",
    featured: true,
    title: "NASA Astronaut Scott Kelly Reflects on His Year in Space",
    publisher: "NASA",
    duration: "Interview",
    url: "https://www.youtube.com/watch?v=pLuY4rDQUyI",
    youtubeId: "pLuY4rDQUyI",
    note: "Primary NASA interview near the end of his 340-day mission, including the biomedical purpose of the mission and the realities of long-duration spaceflight.",
    evidence: "Institutional / primary"
  },
  {
    id: "kelly-time-video",
    person: "Scott Kelly",
    personId: "scott-kelly",
    type: "watch",
    featured: false,
    title: "Scott Kelly Prepares to Spend a Year in Space",
    publisher: "TIME",
    duration: "13m",
    url: "https://www.youtube.com/watch?v=3YfyvA8AxLw",
    youtubeId: "3YfyvA8AxLw",
    note: "A short documentary-style entry point covering risk, family separation, Mars, and the twin-study concept.",
    evidence: "Independent documentary"
  },
  {
    id: "kelly-astroben",
    person: "Scott Kelly",
    personId: "scott-kelly",
    type: "listen",
    featured: false,
    title: "Scott Kelly: NASA's Twin Study and a Year in Space",
    publisher: "The Astro Ben Podcast",
    duration: "Podcast",
    url: "https://astroben.libsyn.com/scott-kelly-astronaut-nasas-twin-study-year-in-space",
    note: "A conversational audio interview about life aboard the ISS, the Twins Study, isolation and the wider space programme.",
    evidence: "Podcast interview"
  },
  {
    id: "kelly-pbs",
    person: "Scott Kelly",
    personId: "scott-kelly",
    type: "watch",
    featured: false,
    title: "A Year in Space / Beyond a Year in Space",
    publisher: "PBS",
    duration: "Documentary",
    url: "https://www.pbs.org/show/year-space/",
    note: "A two-part documentary project focused on the mission and the post-flight scientific question: what did a year in space do to Kelly's body?",
    evidence: "Independent documentary"
  },
  {
    id: "kelly-twins-study",
    person: "Scott Kelly",
    personId: "scott-kelly",
    type: "read",
    featured: false,
    title: "NASA Twins Study",
    publisher: "NASA",
    duration: "Research hub",
    url: "https://www.nasa.gov/humans-in-space/twins-study/",
    note: "The best starting point for the institutional science behind the case, with links into the published findings.",
    evidence: "Institutional / peer-reviewed context"
  }
];

window.RESOURCE_TYPES = {
  watch: { label: "Watch", icon: "▶" },
  listen: { label: "Listen", icon: "◉" },
  read: { label: "Read", icon: "↗" }
};
